services:
  backend:
    container_name: backend
    build:
      context: .
      target: runner
    command:
      - pnpm
      - --filter
      - backend
      - start:prod
    environment:
      NODE_ENV: production
      PORT: "8080"
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    env_file:
      - .env
    ports:
      - "8080:8080"

  web:
    container_name: web
    build:
      context: .
      target: runner
    command:
      - pnpm
      - --filter
      - web
      - exec
      - next
      - start
      - -H
      - 0.0.0.0
      - -p
      - "3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
      DATABASE_URL: ${DATABASE_URL}
      BACKEND_URL: "${BACKEND_URL:-http://backend:8080}"
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
