services:
  backend:
    container_name: backend
    build:
      context: .
      target: runner
    command:
      - pnpm
      - --filter
      - backend
      - start:prod
    environment:
      NODE_ENV: production
      PORT: "${BACKEND_PORT}"
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:3000"

  web:
    container_name: web
    build:
      context: .
      target: runner
    command:
      - pnpm
      - --filter
      - web
      - exec
      - next
      - start
      - -H
      - 0.0.0.0
      - -p
      - "8080"
    environment:
      NODE_ENV: production
      PORT: ${FRONTEND_PORT}
      BACKEND_URL: ${BACKEND_URL}
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:8080"
